### ISSUE TITLE
Fix Travis karma issues

### ISSUE THREAD

**Issue by PVince81** [owncloud/customgroups#100]
JS tests usually run fine locally for me, but for some reason the Travis env is having trouble:

```
/home/travis/build/owncloud/core/apps/customgroups/node_modules/.bin/karma start tests/js/karma.config.js --single-run
/home/travis/build/owncloud/core/apps/customgroups/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/travis/build/owncloud/core/apps/customgroups/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/owncloud/core/apps/customgroups/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)
make: *** [test-js] Error 1
```

**Comment by PVince81** [comment]
Fixed through #101
